# Site settings
title:       wangshelley.com
description: Personal website of Shelley Wang
url:         http://wangshelley.com
locale:      en_US

name:  Shelley Wang
email: shell.bell.wang@gmail.com

permalink: /:categories/:title.html

# Build settings
markdown: kramdown
